import type { Badge } from '@/types/badge';

/**
 * The 23 badges that AppContext can derive automatically from the
 * Trip / TravelStyle data. Initial progress / level values mirror what
 * `computeAbsoluteProgress` produces for the 3 mock trips — so the
 * useEffect re-render is a no-op on first paint.
 */
export const mockBadges: Badge[] = [
  // ========== COLLECTION (5) ==========
  {
    id: 'city-collector',
    name: 'City Collector',
    nameKo: '도시 수집가',
    description: '누적 방문 도시 수',
    icon: '🏙',
    color: '#FB7185',
    level: 1,
    progress: 7,
    nextThreshold: 8,
    thresholds: [3, 8, 15, 25, 50, 100],
    unlockedAt: '2024-02-07',
    category: 'collection',
  },
  {
    id: 'explorer',
    name: 'Explorer',
    nameKo: '탐험가',
    description: '방문한 국가 수',
    icon: '🧭',
    color: '#FCD34D',
    level: 1,
    progress: 3,
    nextThreshold: 5,
    thresholds: [3, 5, 10, 20, 50],
    unlockedAt: '2024-05-12',
    category: 'collection',
  },
  {
    id: 'country-hunter',
    name: 'Country Hunter',
    nameKo: '국가 헌터',
    description: '국경을 넘은 횟수',
    icon: '🌐',
    color: '#FB7185',
    level: 0,
    progress: 2,
    nextThreshold: 3,
    thresholds: [3, 10, 25, 50, 100],
    category: 'collection',
  },
  {
    id: 'korea-master',
    name: 'Korea Master',
    nameKo: '코리아 마스터',
    description: '한국 시·군 수집',
    icon: '🇰🇷',
    color: '#FB7185',
    level: 0,
    progress: 1,
    nextThreshold: 3,
    thresholds: [3, 10, 30, 80, 226],
    category: 'collection',
  },
  {
    id: 'border-crosser',
    name: 'Border Crosser',
    nameKo: '국경 넘는 자',
    description: '한 여행에서 두 국가 이상',
    icon: '🛂',
    color: '#FB7185',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-05-12',
    category: 'collection',
  },

  // ========== PHOTO (2) ==========
  {
    id: 'photographer',
    name: 'Photographer',
    nameKo: '사진가',
    description: '누적 사진 수',
    icon: '📸',
    color: '#A78BFA',
    level: 2,
    progress: 136,
    nextThreshold: 250,
    thresholds: [50, 100, 250, 500, 1000],
    unlockedAt: '2024-02-07',
    category: 'photo',
  },
  {
    id: 'memory-keeper',
    name: 'Memory Keeper',
    nameKo: '추억 보관자',
    description: '누적 사진 (장기 마일스톤)',
    icon: '📁',
    color: '#FB7185',
    level: 1,
    progress: 136,
    nextThreshold: 500,
    thresholds: [100, 500, 1000, 3000, 10000],
    unlockedAt: '2024-02-07',
    category: 'photo',
  },

  // ========== FREQUENCY (11) ==========
  {
    id: 'weekend-traveler',
    name: 'Weekend Traveler',
    nameKo: '주말여행자',
    description: '금/토 시작 + 3일 이내 여행',
    icon: '🎒',
    color: '#F9A8D4',
    level: 0,
    progress: 0,
    nextThreshold: 5,
    thresholds: [5, 10, 20, 40],
    category: 'frequency',
  },
  {
    id: 'monthly-traveler',
    name: 'Monthly Traveler',
    nameKo: '월간 여행자',
    description: '여행한 월 수',
    icon: '📅',
    color: '#FB7185',
    level: 0,
    progress: 2,
    nextThreshold: 3,
    thresholds: [3, 6, 12, 24],
    category: 'frequency',
  },
  {
    id: 'spring-traveler',
    name: 'Spring Traveler',
    nameKo: '봄의 여행자',
    description: '3–5월 시작 여행',
    icon: '🌸',
    color: '#F9A8D4',
    level: 1,
    progress: 2,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-05-12',
    category: 'frequency',
  },
  {
    id: 'summer-traveler',
    name: 'Summer Traveler',
    nameKo: '여름의 여행자',
    description: '6–8월 시작 여행',
    icon: '🏖',
    color: '#FCD34D',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5, 10],
    category: 'frequency',
  },
  {
    id: 'autumn-traveler',
    name: 'Autumn Traveler',
    nameKo: '가을의 여행자',
    description: '9–11월 시작 여행',
    icon: '🍁',
    color: '#FB923C',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5, 10],
    category: 'frequency',
  },
  {
    id: 'winter-traveler',
    name: 'Winter Traveler',
    nameKo: '겨울의 여행자',
    description: '12–2월 시작 여행',
    icon: '❄',
    color: '#A78BFA',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-02-03',
    category: 'frequency',
  },
  {
    id: 'weekday-warrior',
    name: 'Weekday Warrior',
    nameKo: '평일 전사',
    description: '월–목 시작 여행',
    icon: '💼',
    color: '#9CA3AF',
    level: 0,
    progress: 0,
    nextThreshold: 5,
    thresholds: [5, 15, 30, 60],
    category: 'frequency',
  },
  {
    id: 'long-trip',
    name: 'Long Trip',
    nameKo: '장거리 여행자',
    description: '7일 이상 여행',
    icon: '✈',
    color: '#FB7185',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-05-12',
    category: 'frequency',
  },
  {
    id: 'quick-getaway',
    name: 'Quick Getaway',
    nameKo: '짧은 휴식',
    description: '1박 2일 여행',
    icon: '⏱',
    color: '#34D399',
    level: 1,
    progress: 1,
    nextThreshold: 5,
    thresholds: [1, 5, 15, 30],
    unlockedAt: '2024-05-12',
    category: 'frequency',
  },
  {
    id: 'consecutive-month',
    name: 'Consecutive Month',
    nameKo: '연속 여행자',
    description: '연속된 달 streak',
    icon: '🔥',
    color: '#FB7185',
    level: 0,
    progress: 1,
    nextThreshold: 3,
    thresholds: [3, 6, 12],
    category: 'frequency',
  },
  {
    id: 'four-seasons',
    name: 'Four Seasons',
    nameKo: '사계절',
    description: '한 도시 사계절 방문',
    icon: '🌈',
    color: '#A78BFA',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5],
    category: 'frequency',
  },

  // ========== SPECIAL (5) ==========
  {
    id: 'foodie',
    name: 'Foodie',
    nameKo: '미식가',
    description: '미식 여행 스타일 점수',
    icon: '🍜',
    color: '#FB923C',
    level: 3,
    progress: 75,
    nextThreshold: 100,
    thresholds: [10, 25, 50, 100],
    unlockedAt: '2024-02-03',
    category: 'special',
  },
  {
    id: 'solo-explorer',
    name: 'Solo Explorer',
    nameKo: '솔로 탐험가',
    description: '혼자 떠난 여행',
    icon: '🥾',
    color: '#9CA3AF',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-05-12',
    category: 'special',
  },
  {
    id: 'couple-getaway',
    name: 'Couple Getaway',
    nameKo: '커플 여행자',
    description: '둘이서 떠난 여행',
    icon: '💑',
    color: '#F9A8D4',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-05-12',
    category: 'special',
  },
  {
    id: 'first-trip',
    name: 'First Trip',
    nameKo: '첫 여행',
    description: '여행의 시작',
    icon: '⭐',
    color: '#FCD34D',
    level: 1,
    progress: 1,
    nextThreshold: 1,
    thresholds: [1],
    unlockedAt: '2024-02-03',
    category: 'special',
  },
  {
    id: 'milestone-100',
    name: '100 Trips',
    nameKo: '100번째 여행',
    description: '여행 100회 마일스톤',
    icon: '💯',
    color: '#FB7185',
    level: 0,
    progress: 3,
    nextThreshold: 10,
    thresholds: [10, 25, 50, 100],
    category: 'special',
  },
];

export function getBadgeById(id: string): Badge | undefined {
  return mockBadges.find((b) => b.id === id);
}
