import type { Badge } from '@/types/badge';

export const mockBadges: Badge[] = [
  {
    id: 'city-collector',
    name: 'City Collector',
    nameKo: '도시 수집가',
    description: '15개 도시를 방문했어요',
    icon: '🏙',
    color: '#FB7185',
    level: 3,
    progress: 15,
    nextThreshold: 25,
    thresholds: [3, 8, 15, 25, 50, 100],
    unlockedAt: '2024-05-18',
    category: 'collection',
  },
  {
    id: 'explorer',
    name: 'Explorer',
    nameKo: '탐험가',
    description: '5개 국가를 방문했어요',
    icon: '🧭',
    color: '#FCD34D',
    level: 2,
    progress: 7,
    nextThreshold: 10,
    thresholds: [3, 5, 10, 20, 50],
    unlockedAt: '2024-05-15',
    category: 'collection',
  },
  {
    id: 'photographer',
    name: 'Photographer',
    nameKo: '사진가',
    description: '100장의 사진을 기록했어요',
    icon: '📸',
    color: '#A78BFA',
    level: 1,
    progress: 136,
    nextThreshold: 250,
    thresholds: [50, 100, 250, 500, 1000],
    unlockedAt: '2024-02-07',
    category: 'photo',
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    nameKo: '얼리버드',
    description: '오전 6시 이전에 찍은 사진',
    icon: '🌅',
    color: '#34D399',
    level: 0,
    progress: 0,
    nextThreshold: 5,
    thresholds: [5, 15, 30, 60, 100],
    category: 'special',
  },
  {
    id: 'weekend-traveler',
    name: 'Weekend Traveler',
    nameKo: '주말여행자',
    description: '주말 여행 횟수',
    icon: '🎒',
    color: '#F9A8D4',
    level: 0,
    progress: 2,
    nextThreshold: 5,
    thresholds: [5, 10, 20, 40],
    category: 'frequency',
  },
  {
    id: 'foodie',
    name: 'Foodie',
    nameKo: '미식가',
    description: '미식 여행 스타일 점수',
    icon: '🍜',
    color: '#FB923C',
    level: 0,
    progress: 0,
    nextThreshold: 10,
    thresholds: [10, 25, 50, 100],
    category: 'special',
  },
];

export function getBadgeById(id: string): Badge | undefined {
  return mockBadges.find((b) => b.id === id);
}
