import type { Badge } from '@/types/badge';

export const mockBadges: Badge[] = [
  // ========== COLLECTION ==========
  {
    id: 'city-collector',
    name: 'City Collector',
    nameKo: '도시 수집가',
    description: '15개 도시를 방문했어요',
    icon: '🏙',
    color: '#FB7185',
    level: 3,
    progress: 15,
    nextThreshold: 25,
    thresholds: [3, 8, 15, 25, 50, 100],
    unlockedAt: '2024-05-18',
    category: 'collection',
  },
  {
    id: 'explorer',
    name: 'Explorer',
    nameKo: '탐험가',
    description: '5개 국가를 방문했어요',
    icon: '🧭',
    color: '#FCD34D',
    level: 2,
    progress: 7,
    nextThreshold: 10,
    thresholds: [3, 5, 10, 20, 50],
    unlockedAt: '2024-05-15',
    category: 'collection',
  },
  {
    id: 'country-hunter',
    name: 'Country Hunter',
    nameKo: '국가 헌터',
    description: '국경을 넘어 여행한 횟수',
    icon: '🌐',
    color: '#FB7185',
    level: 1,
    progress: 5,
    nextThreshold: 10,
    thresholds: [3, 10, 25, 50, 100],
    unlockedAt: '2024-05-12',
    category: 'collection',
  },
  {
    id: 'continent-walker',
    name: 'Continent Walker',
    nameKo: '대륙 워커',
    description: '대륙별 여행',
    icon: '🌍',
    color: '#34D399',
    level: 1,
    progress: 3,
    nextThreshold: 5,
    thresholds: [2, 5, 7],
    unlockedAt: '2024-05-12',
    category: 'collection',
  },
  {
    id: 'korea-master',
    name: 'Korea Master',
    nameKo: '코리아 마스터',
    description: '한국 시·군 수집',
    icon: '🇰🇷',
    color: '#FB7185',
    level: 2,
    progress: 12,
    nextThreshold: 30,
    thresholds: [3, 10, 30, 80, 226],
    unlockedAt: '2024-02-03',
    category: 'collection',
  },
  {
    id: 'asia-explorer',
    name: 'Asia Explorer',
    nameKo: '아시아 탐험가',
    description: '아시아 도·주 수집',
    icon: '🏯',
    color: '#FCD34D',
    level: 1,
    progress: 2,
    nextThreshold: 5,
    thresholds: [2, 5, 10, 20, 40],
    unlockedAt: '2024-02-03',
    category: 'collection',
  },
  {
    id: 'europe-explorer',
    name: 'Europe Explorer',
    nameKo: '유럽 탐험가',
    description: '유럽 도·주 수집',
    icon: '🏰',
    color: '#A78BFA',
    level: 1,
    progress: 2,
    nextThreshold: 5,
    thresholds: [2, 5, 10, 25, 50],
    unlockedAt: '2024-05-12',
    category: 'collection',
  },
  {
    id: 'americas-explorer',
    name: 'Americas Explorer',
    nameKo: '아메리카 탐험가',
    description: '아메리카 대륙 도·주',
    icon: '🗽',
    color: '#FB923C',
    level: 0,
    progress: 0,
    nextThreshold: 2,
    thresholds: [2, 5, 10, 25, 50],
    category: 'collection',
  },
  {
    id: 'africa-explorer',
    name: 'Africa Explorer',
    nameKo: '아프리카 탐험가',
    description: '아프리카 대륙 도·주',
    icon: '🦁',
    color: '#FCD34D',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5, 10],
    category: 'collection',
  },
  {
    id: 'oceania-explorer',
    name: 'Oceania Explorer',
    nameKo: '오세아니아 탐험가',
    description: '오세아니아 도·주',
    icon: '🐨',
    color: '#34D399',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5, 8],
    category: 'collection',
  },
  {
    id: 'island-hopper',
    name: 'Island Hopper',
    nameKo: '섬 호퍼',
    description: '섬 지역 방문',
    icon: '🏝',
    color: '#34D399',
    level: 1,
    progress: 1,
    nextThreshold: 5,
    thresholds: [1, 5, 10, 20],
    unlockedAt: '2024-02-03',
    category: 'collection',
  },
  {
    id: 'coastal-traveler',
    name: 'Coastal Traveler',
    nameKo: '해안 여행자',
    description: '바닷가 도시 방문',
    icon: '🌊',
    color: '#34D399',
    level: 1,
    progress: 2,
    nextThreshold: 5,
    thresholds: [2, 5, 10, 20],
    unlockedAt: '2024-02-03',
    category: 'collection',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    nameKo: '산악인',
    description: '산악 지역 방문',
    icon: '⛰',
    color: '#9CA3AF',
    level: 0,
    progress: 0,
    nextThreshold: 3,
    thresholds: [3, 10, 25, 50],
    category: 'collection',
  },
  {
    id: 'capital-collector',
    name: 'Capital Collector',
    nameKo: '수도 수집가',
    description: '각국 수도 방문',
    icon: '🏛',
    color: '#FB7185',
    level: 1,
    progress: 2,
    nextThreshold: 5,
    thresholds: [2, 5, 10, 20, 50],
    unlockedAt: '2024-05-12',
    category: 'collection',
  },
  {
    id: 'unesco-seeker',
    name: 'UNESCO Seeker',
    nameKo: '유네스코 헌터',
    description: '세계유산 방문',
    icon: '🛕',
    color: '#FCD34D',
    level: 0,
    progress: 1,
    nextThreshold: 3,
    thresholds: [3, 10, 25, 50, 100],
    category: 'collection',
  },
  {
    id: 'small-town-lover',
    name: 'Small Town Lover',
    nameKo: '소도시 애호가',
    description: '인구 10만 이하 군 방문',
    icon: '🏘',
    color: '#FED7AA',
    level: 1,
    progress: 1,
    nextThreshold: 5,
    thresholds: [1, 5, 15, 30],
    unlockedAt: '2023-09-10',
    category: 'collection',
  },
  {
    id: 'metropolis-fan',
    name: 'Metropolis Fan',
    nameKo: '메트로폴리스 팬',
    description: '인구 100만 이상 도시',
    icon: '🌆',
    color: '#A78BFA',
    level: 1,
    progress: 3,
    nextThreshold: 5,
    thresholds: [1, 5, 10, 25],
    unlockedAt: '2024-02-03',
    category: 'collection',
  },
  {
    id: 'border-crosser',
    name: 'Border Crosser',
    nameKo: '국경 넘는 자',
    description: '한 여행에서 두 국가 이상',
    icon: '🛂',
    color: '#FB7185',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-05-12',
    category: 'collection',
  },

  // ========== PHOTO ==========
  {
    id: 'photographer',
    name: 'Photographer',
    nameKo: '사진가',
    description: '100장의 사진을 기록했어요',
    icon: '📸',
    color: '#A78BFA',
    level: 1,
    progress: 136,
    nextThreshold: 250,
    thresholds: [50, 100, 250, 500, 1000],
    unlockedAt: '2024-02-07',
    category: 'photo',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    nameKo: '골든 아워',
    description: '해질녘 시간대 사진',
    icon: '🌇',
    color: '#FB923C',
    level: 1,
    progress: 12,
    nextThreshold: 30,
    thresholds: [5, 30, 100, 300],
    unlockedAt: '2024-05-15',
    category: 'photo',
  },
  {
    id: 'blue-hour',
    name: 'Blue Hour',
    nameKo: '블루 아워',
    description: '동트기 직전 사진',
    icon: '🌌',
    color: '#A78BFA',
    level: 0,
    progress: 0,
    nextThreshold: 5,
    thresholds: [5, 20, 60, 150],
    category: 'photo',
  },
  {
    id: 'portrait-pro',
    name: 'Portrait Pro',
    nameKo: '인물 사진가',
    description: '인물 사진 모음',
    icon: '🤳',
    color: '#F9A8D4',
    level: 1,
    progress: 28,
    nextThreshold: 50,
    thresholds: [10, 50, 150, 400],
    unlockedAt: '2024-02-07',
    category: 'photo',
  },
  {
    id: 'landscape-master',
    name: 'Landscape Master',
    nameKo: '풍경 마스터',
    description: '풍경 사진 모음',
    icon: '🏞',
    color: '#34D399',
    level: 1,
    progress: 60,
    nextThreshold: 100,
    thresholds: [20, 100, 300, 700],
    unlockedAt: '2024-02-07',
    category: 'photo',
  },
  {
    id: 'food-blogger',
    name: 'Food Blogger',
    nameKo: '푸드 블로거',
    description: '음식 사진 모음',
    icon: '🍽',
    color: '#FB923C',
    level: 0,
    progress: 8,
    nextThreshold: 15,
    thresholds: [15, 50, 150, 400],
    category: 'photo',
  },
  {
    id: 'street-shooter',
    name: 'Street Shooter',
    nameKo: '스트릿 슈터',
    description: '거리 사진 모음',
    icon: '🚶',
    color: '#9CA3AF',
    level: 0,
    progress: 0,
    nextThreshold: 20,
    thresholds: [20, 100, 300, 700],
    category: 'photo',
  },
  {
    id: 'memory-keeper',
    name: 'Memory Keeper',
    nameKo: '추억 보관자',
    description: '누적 사진 수',
    icon: '📁',
    color: '#FB7185',
    level: 1,
    progress: 136,
    nextThreshold: 500,
    thresholds: [100, 500, 1000, 3000, 10000],
    unlockedAt: '2024-02-07',
    category: 'photo',
  },

  // ========== FREQUENCY ==========
  {
    id: 'weekend-traveler',
    name: 'Weekend Traveler',
    nameKo: '주말여행자',
    description: '주말 여행 횟수',
    icon: '🎒',
    color: '#F9A8D4',
    level: 0,
    progress: 2,
    nextThreshold: 5,
    thresholds: [5, 10, 20, 40],
    category: 'frequency',
  },
  {
    id: 'monthly-traveler',
    name: 'Monthly Traveler',
    nameKo: '월간 여행자',
    description: '한 달에 한 번 이상',
    icon: '📅',
    color: '#FB7185',
    level: 1,
    progress: 3,
    nextThreshold: 6,
    thresholds: [3, 6, 12, 24],
    unlockedAt: '2024-02-03',
    category: 'frequency',
  },
  {
    id: 'spring-traveler',
    name: 'Spring Traveler',
    nameKo: '봄의 여행자',
    description: '봄철 여행 횟수',
    icon: '🌸',
    color: '#F9A8D4',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-05-12',
    category: 'frequency',
  },
  {
    id: 'summer-traveler',
    name: 'Summer Traveler',
    nameKo: '여름의 여행자',
    description: '여름철 여행 횟수',
    icon: '🏖',
    color: '#FCD34D',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5, 10],
    category: 'frequency',
  },
  {
    id: 'autumn-traveler',
    name: 'Autumn Traveler',
    nameKo: '가을의 여행자',
    description: '가을철 여행 횟수',
    icon: '🍁',
    color: '#FB923C',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2023-09-10',
    category: 'frequency',
  },
  {
    id: 'winter-traveler',
    name: 'Winter Traveler',
    nameKo: '겨울의 여행자',
    description: '겨울철 여행 횟수',
    icon: '❄',
    color: '#A78BFA',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-02-03',
    category: 'frequency',
  },
  {
    id: 'weekday-warrior',
    name: 'Weekday Warrior',
    nameKo: '평일 전사',
    description: '평일에 떠난 여행',
    icon: '💼',
    color: '#9CA3AF',
    level: 0,
    progress: 1,
    nextThreshold: 5,
    thresholds: [5, 15, 30, 60],
    category: 'frequency',
  },
  {
    id: 'holiday-hunter',
    name: 'Holiday Hunter',
    nameKo: '공휴일 헌터',
    description: '공휴일 여행 횟수',
    icon: '🎌',
    color: '#FCD34D',
    level: 0,
    progress: 1,
    nextThreshold: 5,
    thresholds: [5, 15, 30],
    category: 'frequency',
  },
  {
    id: 'long-trip',
    name: 'Long Trip',
    nameKo: '장거리 여행자',
    description: '7일 이상 여행',
    icon: '✈',
    color: '#FB7185',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-05-12',
    category: 'frequency',
  },
  {
    id: 'quick-getaway',
    name: 'Quick Getaway',
    nameKo: '짧은 휴식',
    description: '1박 2일 여행',
    icon: '⏱',
    color: '#34D399',
    level: 1,
    progress: 1,
    nextThreshold: 5,
    thresholds: [1, 5, 15, 30],
    unlockedAt: '2024-05-12',
    category: 'frequency',
  },
  {
    id: 'consecutive-month',
    name: 'Consecutive Month',
    nameKo: '연속 여행자',
    description: '연속된 달에 여행',
    icon: '🔥',
    color: '#FB7185',
    level: 0,
    progress: 0,
    nextThreshold: 3,
    thresholds: [3, 6, 12],
    category: 'frequency',
  },
  {
    id: 'four-seasons',
    name: 'Four Seasons',
    nameKo: '사계절',
    description: '한 도시 사계절 방문',
    icon: '🌈',
    color: '#A78BFA',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5],
    category: 'frequency',
  },

  // ========== SPECIAL ==========
  {
    id: 'early-bird',
    name: 'Early Bird',
    nameKo: '얼리버드',
    description: '오전 6시 이전에 찍은 사진',
    icon: '🌅',
    color: '#34D399',
    level: 0,
    progress: 0,
    nextThreshold: 5,
    thresholds: [5, 15, 30, 60, 100],
    category: 'special',
  },
  {
    id: 'foodie',
    name: 'Foodie',
    nameKo: '미식가',
    description: '미식 여행 스타일 점수',
    icon: '🍜',
    color: '#FB923C',
    level: 0,
    progress: 0,
    nextThreshold: 10,
    thresholds: [10, 25, 50, 100],
    category: 'special',
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    nameKo: '야행성',
    description: '자정 이후 사진',
    icon: '🌙',
    color: '#A78BFA',
    level: 0,
    progress: 0,
    nextThreshold: 5,
    thresholds: [5, 20, 50, 100],
    category: 'special',
  },
  {
    id: 'coffee-lover',
    name: 'Coffee Lover',
    nameKo: '커피 애호가',
    description: '카페 방문 기록',
    icon: '☕',
    color: '#FB923C',
    level: 0,
    progress: 0,
    nextThreshold: 5,
    thresholds: [5, 20, 50, 100],
    category: 'special',
  },
  {
    id: 'dessert-hunter',
    name: 'Dessert Hunter',
    nameKo: '디저트 헌터',
    description: '디저트 사진',
    icon: '🍰',
    color: '#F9A8D4',
    level: 0,
    progress: 0,
    nextThreshold: 5,
    thresholds: [5, 20, 50, 100],
    category: 'special',
  },
  {
    id: 'wine-traveler',
    name: 'Wine Traveler',
    nameKo: '와인 여행자',
    description: '와인 산지 방문',
    icon: '🍷',
    color: '#FB7185',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5, 10],
    category: 'special',
  },
  {
    id: 'festival-goer',
    name: 'Festival Goer',
    nameKo: '축제 참여자',
    description: '축제 기간 여행',
    icon: '🎉',
    color: '#FCD34D',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5, 10],
    category: 'special',
  },
  {
    id: 'solo-explorer',
    name: 'Solo Explorer',
    nameKo: '솔로 탐험가',
    description: '혼자 떠난 여행',
    icon: '🥾',
    color: '#9CA3AF',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2023-09-10',
    category: 'special',
  },
  {
    id: 'family-tripper',
    name: 'Family Tripper',
    nameKo: '가족 여행자',
    description: '가족과 함께한 여행',
    icon: '👨‍👩‍👧',
    color: '#FCD34D',
    level: 0,
    progress: 0,
    nextThreshold: 1,
    thresholds: [1, 3, 5, 10],
    category: 'special',
  },
  {
    id: 'couple-getaway',
    name: 'Couple Getaway',
    nameKo: '커플 여행자',
    description: '둘이서 떠난 여행',
    icon: '💑',
    color: '#F9A8D4',
    level: 1,
    progress: 1,
    nextThreshold: 3,
    thresholds: [1, 3, 5, 10],
    unlockedAt: '2024-02-03',
    category: 'special',
  },
  {
    id: 'first-trip',
    name: 'First Trip',
    nameKo: '첫 여행',
    description: '여행의 시작',
    icon: '⭐',
    color: '#FCD34D',
    level: 1,
    progress: 1,
    nextThreshold: 1,
    thresholds: [1],
    unlockedAt: '2023-09-10',
    category: 'special',
  },
  {
    id: 'milestone-100',
    name: '100 Trips',
    nameKo: '100번째 여행',
    description: '여행 100회 마일스톤',
    icon: '💯',
    color: '#FB7185',
    level: 0,
    progress: 3,
    nextThreshold: 10,
    thresholds: [10, 25, 50, 100],
    category: 'special',
  },
];

export function getBadgeById(id: string): Badge | undefined {
  return mockBadges.find((b) => b.id === id);
}
